# Generated by Django 4.2.1 on 2023-05-15 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mainuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=250, unique=True)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("contact_no", models.CharField(max_length=250)),
                ("date_joined", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=0)),
                (
                    "e_u_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
