# Generated by Django 4.2.1 on 2023-05-15 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainuser", "0002_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 15, 10, 47, 54, 415466, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
