# Generated by Django 4.2.1 on 2023-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainuser", "0005_alter_employee_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
