# Generated by Django 4.2.1 on 2023-05-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainuser", "0008_rename_role_user_role_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="designation_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainuser.designationhead",
            ),
        ),
    ]
