# Generated by Django 4.2.1 on 2023-05-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainuser", "0009_designation_designation_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="designation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainuser.designation",
            ),
        ),
    ]
